### PR TITLE
removing "that guy"

### PR DESCRIPTION
**Pull request by lmccart**
Changing to a gender-neutral item title. I'm not sure this is the right title, but seeing the page end with the phrase "that guy" makes me think maybe only guys are wanted or expected here.

### CODE REVIEW

**Comment by lmccart** [comment]
I signed it!

**Comment by rspier** [comment]
Hi Lauren,

  Sorry for the delayed response.

  I don't think "Mentorable" is the right phrasing either.

  One simple approach could be to just call it "Pro Tip #2" -- but it might need another sentence at the end to flesh it out.  "Ideas without potential mentors aren't useful to anyone." or similar.

   What do you think?

-R

**Comment by lmccart** [comment]
@rspier that sounds good to me. or maybe just changing "that guy" to "that person"? 😄 
I'm also fine if you want to close this completely, just wanted to leave the note in case it's helpful, because seeing that phrase as the closing statement on the page just felt a little surprising.

**Comment by rspier** [comment]
Changing to "that person" is definitely the simplest solution.  I think we definitely should make a change -- since you brought attention to it, that whole paragraph sticks out a bit -- but we can deal with one issue at a time.

Urban Dictionary (caution, may contain disagreeable content) describes "that guy" as "The person everyone loves to hate and never wants to become." which is a good description of the person who submits ideas that no-one including the submitter would want to mentor.  

I'm not sure if "that person" is as clear as "that guy" but the readers will figure it out.  And many of them may not be familiar with the idiom anyway.

Update the PR?

Thanks-

**Pull request closed without merging**
