### PR TITLE
header logo issue

### PR DESCRIPTION
**Pull request by fiorellarc05**
to solve the header logo issue, I made a new image that can help

### CODE REVIEW

**Comment by fiorellarc05** [comment]
@googlebot I signed it!

**Comment by rspier** [comment]
What's wrong with the existing logo?

**Comment by fiorellarc05** [comment]
There's an open issue with the logo, I thought maybe you still need help with that

**Comment by rspier** [comment]
Got it, thanks.

Thank you for sending the PR, but.

I'm going to reject this PR because it doesn't just make the logo slightly bigger, but also changes the logo to something different.  It's also a huge image, from 4k to 263k.

Increasing the size of the current image isn't just about making the image bigger, but the CSS needs tweaking too.

**Pull request closed without merging**
